In [1]:
import pandas as pd

In [25]:
df = pd.read_csv('greenbook.csv')
df1 = pd.read_csv('orderbook.csv')

In [26]:
df['Fee'] = df['Fee'].str.strip()
df['Fee'] = df['Fee'].str.replace(',', '', regex=True)
df['Fee'].fillna(0,inplace=True)
df['Fee'] = df['Fee'].astype('int64')
# df['Fee'] = df['Fee'].str.strip()
# df['Fee'] = df['Fee'].str.replace(',', '', regex=True)
# df['Fee'].fillna(0,inplace=True)

/var/folders/z3/qcprk3q91f1dz178lc4c76mr0000gn/T/ipykernel_29361/3844784274.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fee'].fillna(0,inplace=True)

In [27]:
df.fillna('',inplace=True)

In [28]:
df

,Nama Perusahaan,Pekerjaan,Fee,PIC,SCHEDULE INVOICE,ESTIMASI CASH IN
0,PT ABM Investama Tbk,FDD project biru,220000000,,,
1,PT Globalization Partners Indonesia,Audit 31 Desember 2024,10500000,RANGGA,MARET,MARET
2,PT Globalization Partners Indonesia,Audit 31 Desember 2024,17500000,RANGGA,MARET,APRIL
3,PT Globalization Partners Indonesia,Audit 31 Desember 2024,7000000,RANGGA,APRIL,MEI
4,PT Sany Heavy Industry Indonesia,Audit 31 Desember 2024,30000000,"RANGGA, STEFANI",MARET,MARET
5,PT Sany Heavy Industry Indonesia,Audit 31 Desember 2024,50000000,"RANGGA, STEFANI",APRIL,MEI
6,PT Sany Heavy Industry Indonesia,Audit 31 Desember 2024,20000000,"RANGGA, STEFANI",MEI,JUNI
7,PT Sany Indonesia Heavy Equipment,Audit 31 Desember 2024,22500000,"RANGGA, STEFANI",MARET,MARET
8,PT Sany Indonesia Heavy Equipment,Audit 31 Desember 2024,37500000,"RANGGA, STEFANI",APRIL,MEI
9,PT Sany Indonesia Heavy Equipment,Audit 31 Desember 2024,15000000,"RANGGA, STEFANI",MEI,JUNI
10,PT Sany Indonesia Machinery,Audit 31 Desember 2024,52500000,"RANGGA, STEFANI",MARET,MARET
11,PT Sany Indonesia Machinery,Audit 31 Desember 2024,87500000,"RANGGA, STEFANI",APRIL,MEI
12,PT Sany Indonesia Machinery,Audit 31 Desember 2024,35000000,"RANGGA, STEFANI",MEI,JUNI
13,PT Sany Indonesia Mining Equipment,Audit 31 Desember 2024,22500000,"RANGGA, STEFANI",MARET,MARET
14,PT Sany Indonesia Mining Equipment,Audit 31 Desember 2024,37500000,"RANGGA, STEFANI",APRIL,MEI
15,PT Sany Indonesia Mining Equipment,Audit 31 Desember 2024,15000000,"RANGGA, STEFANI",MEI,JUNI
16,PT Agri Hikay,KPPK 31 Des 2024,6250000,GRESSY,MARET,MARET
17,PT Agri Hikay,KPPK 31 Des 2024,6250000,LAYLA,JUNI,JULI
18,PT Agri Indomas,KPPK 31 Des 2024,6250000,GRESSY,MARET,MARET
19,PT Agri Indomas,KPPK 31 Des 2024,6250000,LAYLA,JUNI,JULI
20,PT Petro Andalan Nusantara,KPPK 31 Des 2024,6250000,GRESSY,MARET,MARET
21,PT Petro Andalan Nusantara,KPPK 31 Des 2024,6250000,LAYLA,JUNI,JULI
22,PT Sentana Adidaya,KPPK 31 Des 2024,6250000,GRESSY,MARET,MARET
23,PT Sentana Adidaya,KPPK 31 Des 2024,6250000,LAYLA,JUNI,JULI
24,Undip,PSAK 71 dan 73,90000000,SALLY,MARET,MARET
25,Undip,PSAK 71 dan 73,90000000,SALLY,APRIL,MEI
26,PT Aria Hijau Alamlestari,Audit 31 Des 2024,82250000,,,
27,PT Dayamitra Telekomunikasi,Pendampingan implementasi PSAK 71 2025,120000000,,,
28,PT Hexindo,Pendampingan implementasi PSAK 71 31 Maret 2025,75000000,,,
29,PT Kereta Api Indonesia (Persero) Tbk,ICOFR,4150000000,,,
30,PT Liebherr Indonesia Perkasa,KPPK 31 Des 2024,24000000,,,
31,PT Chitra Paratama,KPPK 31 Des 2024,16500000,,,
32,PT JGC Indonesia,KPPK 31 Des 2024,14300000,,,
33,Komunika Jaya Nusantara,Audit 31 Des 2022 dan 2023,90000000,,,
34,PT Medco Power Indonesia,KPPK 31 Des 2024,17500000,,,
35,PT Medco Ratch Power Riau,KPPK 31 Des 2024,17500000,,,
36,PT Medco Energy Internasional,KPPK 31 Des 2024,17500000,,,
37,PT Medco EP Tomori Sulawesi,KPPK 31 Des 2024,17500000,,,
38,PT Medco EP Malaka,KPPK 31 Des 2024,17500000,,,
39,Agro Hope,KPPK 31 Des 2024,120000000,,,
40,PT Chandra Sakti Utama Leasing,KPPK 31 Des 2024,16500000,,,

In [29]:
df.groupby(['Nama Perusahaan', 'Pekerjaan'])['Fee'].sum().reset_index()

,Nama Perusahaan,Pekerjaan,Fee
0,Agro Hope,KPPK 31 Des 2024,120000000
1,Komunika Jaya Nusantara,Audit 31 Des 2022 dan 2023,90000000
2,PT ABM Investama Tbk,FDD project biru,220000000
3,PT Agri Hikay,KPPK 31 Des 2024,12500000
4,PT Agri Indomas,KPPK 31 Des 2024,12500000
5,PT Aria Hijau Alamlestari,Audit 31 Des 2024,82250000
6,PT Chandra Sakti Utama Leasing,KPPK 31 Des 2024,16500000
7,PT Chitra Paratama,KPPK 31 Des 2024,16500000
8,PT Dayamitra Telekomunikasi,Pendampingan implementasi PSAK 71 2025,120000000
9,PT Globalization Partners Indonesia,Audit 31 Desember 2024,35000000
10,PT Hexindo,Pendampingan implementasi PSAK 71 31 Maret 2025,75000000
11,PT JGC Indonesia,KPPK 31 Des 2024,14300000
12,PT Kereta Api Indonesia (Persero) Tbk,ICOFR,4150000000
13,PT Liebherr Indonesia Perkasa,KPPK 31 Des 2024,24000000
14,PT Medco EP Malaka,KPPK 31 Des 2024,17500000
15,PT Medco EP Tomori Sulawesi,KPPK 31 Des 2024,17500000
16,PT Medco Energy Internasional,KPPK 31 Des 2024,17500000
17,PT Medco Power Indonesia,KPPK 31 Des 2024,17500000
18,PT Medco Ratch Power Riau,KPPK 31 Des 2024,17500000
19,PT Petro Andalan Nusantara,KPPK 31 Des 2024,12500000
20,PT Sany Heavy Industry Indonesia,Audit 31 Desember 2024,100000000
21,PT Sany Indonesia Heavy Equipment,Audit 31 Desember 2024,75000000
22,PT Sany Indonesia Machinery,Audit 31 Desember 2024,175000000
23,PT Sany Indonesia Mining Equipment,Audit 31 Desember 2024,75000000
24,PT Sentana Adidaya,KPPK 31 Des 2024,12500000
25,Undip,PSAK 71 dan 73,180000000